In [2]:
import numpy as np


Basics


In [14]:
a = np.array( [1,2,3], dtype = 'int16' )
print(a)

[1 2 3]


In [7]:
b = np.array([ [2,3], [4,5]])
print(b)

[[2 3]
 [4 5]]


Get Dimensions


In [8]:
a.ndim

1

In [9]:
b.ndim

2

Get Shape

In [11]:
b.shape

(2, 2)

In [15]:
# Get Type
a.dtype

dtype('int16')

In [13]:
b.dtype

dtype('int64')

In [16]:
# Get Size in bytes
a.itemsize

2

In [20]:
#Get total size
a.nbytes

6

# Accessing/ Changing Specific elements , rows and columns,etc

In [23]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14 ]] )
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
#Get Specific element
print(a[0,6])


7


In [28]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
# Get a specific columns
a [: , 5]

array([ 6, 13])

In [30]:
# Getting little more fancy  [startindex:endindex:stepsize]
a[0,1:5:2]

array([2, 4])

In [35]:
a[0,6] = 8
a

array([[ 1,  2,  3,  4,  5,  6,  8],
       [ 8,  9, 10, 11, 12, 13, 14]])